// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

type HealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthService) EXPECT() *HealthService_Expecter {
	return &HealthService_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *HealthService) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HealthService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type HealthService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthService_Expecter) Ping(ctx interface{}) *HealthService_Ping_Call {
	return &HealthService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *HealthService_Ping_Call) Run(run func(ctx context.Context)) *HealthService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HealthService_Ping_Call) Return(_a0 error) *HealthService_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthService_Ping_Call) RunAndReturn(run func(context.Context) error) *HealthService_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
