quiet: False
resolve-type-alias: False
issue-845-fix: True
with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
packages:
    github.com/dtroode/urlshorter/internal/app/handler:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            Service:
                config:
    github.com/dtroode/urlshorter/internal/app/service:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            Storage:
                config: