// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dtroode/urlshorter/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetURL provides a mock function with given fields: ctx, shortKey
func (_m *Storage) GetURL(ctx context.Context, shortKey string) (*string, error) {
	ret := _m.Called(ctx, shortKey)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, shortKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, shortKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type Storage_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - shortKey string
func (_e *Storage_Expecter) GetURL(ctx interface{}, shortKey interface{}) *Storage_GetURL_Call {
	return &Storage_GetURL_Call{Call: _e.mock.On("GetURL", ctx, shortKey)}
}

func (_c *Storage_GetURL_Call) Run(run func(ctx context.Context, shortKey string)) *Storage_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetURL_Call) Return(_a0 *string, _a1 error) *Storage_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetURL_Call) RunAndReturn(run func(context.Context, string) (*string, error)) *Storage_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetURL provides a mock function with given fields: ctx, url
func (_m *Storage) SetURL(ctx context.Context, url *model.URL) error {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for SetURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.URL) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_SetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetURL'
type Storage_SetURL_Call struct {
	*mock.Call
}

// SetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url *model.URL
func (_e *Storage_Expecter) SetURL(ctx interface{}, url interface{}) *Storage_SetURL_Call {
	return &Storage_SetURL_Call{Call: _e.mock.On("SetURL", ctx, url)}
}

func (_c *Storage_SetURL_Call) Run(run func(ctx context.Context, url *model.URL)) *Storage_SetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.URL))
	})
	return _c
}

func (_c *Storage_SetURL_Call) Return(_a0 error) *Storage_SetURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_SetURL_Call) RunAndReturn(run func(context.Context, *model.URL) error) *Storage_SetURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
