// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/dtroode/urlshorter/internal/model"

	uuid "github.com/google/uuid"
)

// URLStorage is an autogenerated mock type for the URLStorage type
type URLStorage struct {
	mock.Mock
}

type URLStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *URLStorage) EXPECT() *URLStorage_Expecter {
	return &URLStorage_Expecter{mock: &_m.Mock}
}

// DeleteURLs provides a mock function with given fields: ctx, ids
func (_m *URLStorage) DeleteURLs(ctx context.Context, ids []uuid.UUID) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// URLStorage_DeleteURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLs'
type URLStorage_DeleteURLs_Call struct {
	*mock.Call
}

// DeleteURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *URLStorage_Expecter) DeleteURLs(ctx interface{}, ids interface{}) *URLStorage_DeleteURLs_Call {
	return &URLStorage_DeleteURLs_Call{Call: _e.mock.On("DeleteURLs", ctx, ids)}
}

func (_c *URLStorage_DeleteURLs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *URLStorage_DeleteURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *URLStorage_DeleteURLs_Call) Return(_a0 error) *URLStorage_DeleteURLs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *URLStorage_DeleteURLs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) error) *URLStorage_DeleteURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: ctx, shortKey
func (_m *URLStorage) GetURL(ctx context.Context, shortKey string) (*model.URL, error) {
	ret := _m.Called(ctx, shortKey)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 *model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.URL, error)); ok {
		return rf(ctx, shortKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.URL); ok {
		r0 = rf(ctx, shortKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLStorage_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type URLStorage_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - shortKey string
func (_e *URLStorage_Expecter) GetURL(ctx interface{}, shortKey interface{}) *URLStorage_GetURL_Call {
	return &URLStorage_GetURL_Call{Call: _e.mock.On("GetURL", ctx, shortKey)}
}

func (_c *URLStorage_GetURL_Call) Run(run func(ctx context.Context, shortKey string)) *URLStorage_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *URLStorage_GetURL_Call) Return(_a0 *model.URL, _a1 error) *URLStorage_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLStorage_GetURL_Call) RunAndReturn(run func(context.Context, string) (*model.URL, error)) *URLStorage_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function with given fields: ctx, shortKeys
func (_m *URLStorage) GetURLs(ctx context.Context, shortKeys []string) ([]*model.URL, error) {
	ret := _m.Called(ctx, shortKeys)

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []*model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.URL, error)); ok {
		return rf(ctx, shortKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.URL); ok {
		r0 = rf(ctx, shortKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, shortKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLStorage_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type URLStorage_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - shortKeys []string
func (_e *URLStorage_Expecter) GetURLs(ctx interface{}, shortKeys interface{}) *URLStorage_GetURLs_Call {
	return &URLStorage_GetURLs_Call{Call: _e.mock.On("GetURLs", ctx, shortKeys)}
}

func (_c *URLStorage_GetURLs_Call) Run(run func(ctx context.Context, shortKeys []string)) *URLStorage_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *URLStorage_GetURLs_Call) Return(_a0 []*model.URL, _a1 error) *URLStorage_GetURLs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLStorage_GetURLs_Call) RunAndReturn(run func(context.Context, []string) ([]*model.URL, error)) *URLStorage_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLsByUserID provides a mock function with given fields: ctx, userID
func (_m *URLStorage) GetURLsByUserID(ctx context.Context, userID uuid.UUID) ([]*model.URL, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetURLsByUserID")
	}

	var r0 []*model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.URL, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.URL); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLStorage_GetURLsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLsByUserID'
type URLStorage_GetURLsByUserID_Call struct {
	*mock.Call
}

// GetURLsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *URLStorage_Expecter) GetURLsByUserID(ctx interface{}, userID interface{}) *URLStorage_GetURLsByUserID_Call {
	return &URLStorage_GetURLsByUserID_Call{Call: _e.mock.On("GetURLsByUserID", ctx, userID)}
}

func (_c *URLStorage_GetURLsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *URLStorage_GetURLsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *URLStorage_GetURLsByUserID_Call) Return(_a0 []*model.URL, _a1 error) *URLStorage_GetURLsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLStorage_GetURLsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.URL, error)) *URLStorage_GetURLsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SetURL provides a mock function with given fields: ctx, url
func (_m *URLStorage) SetURL(ctx context.Context, url *model.URL) (*model.URL, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for SetURL")
	}

	var r0 *model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.URL) (*model.URL, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.URL) *model.URL); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.URL) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLStorage_SetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetURL'
type URLStorage_SetURL_Call struct {
	*mock.Call
}

// SetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url *model.URL
func (_e *URLStorage_Expecter) SetURL(ctx interface{}, url interface{}) *URLStorage_SetURL_Call {
	return &URLStorage_SetURL_Call{Call: _e.mock.On("SetURL", ctx, url)}
}

func (_c *URLStorage_SetURL_Call) Run(run func(ctx context.Context, url *model.URL)) *URLStorage_SetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.URL))
	})
	return _c
}

func (_c *URLStorage_SetURL_Call) Return(_a0 *model.URL, _a1 error) *URLStorage_SetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLStorage_SetURL_Call) RunAndReturn(run func(context.Context, *model.URL) (*model.URL, error)) *URLStorage_SetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetURLs provides a mock function with given fields: ctx, urls
func (_m *URLStorage) SetURLs(ctx context.Context, urls []*model.URL) ([]*model.URL, error) {
	ret := _m.Called(ctx, urls)

	if len(ret) == 0 {
		panic("no return value specified for SetURLs")
	}

	var r0 []*model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.URL) ([]*model.URL, error)); ok {
		return rf(ctx, urls)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*model.URL) []*model.URL); ok {
		r0 = rf(ctx, urls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*model.URL) error); ok {
		r1 = rf(ctx, urls)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLStorage_SetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetURLs'
type URLStorage_SetURLs_Call struct {
	*mock.Call
}

// SetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - urls []*model.URL
func (_e *URLStorage_Expecter) SetURLs(ctx interface{}, urls interface{}) *URLStorage_SetURLs_Call {
	return &URLStorage_SetURLs_Call{Call: _e.mock.On("SetURLs", ctx, urls)}
}

func (_c *URLStorage_SetURLs_Call) Run(run func(ctx context.Context, urls []*model.URL)) *URLStorage_SetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*model.URL))
	})
	return _c
}

func (_c *URLStorage_SetURLs_Call) Return(savedURLs []*model.URL, err error) *URLStorage_SetURLs_Call {
	_c.Call.Return(savedURLs, err)
	return _c
}

func (_c *URLStorage_SetURLs_Call) RunAndReturn(run func(context.Context, []*model.URL) ([]*model.URL, error)) *URLStorage_SetURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewURLStorage creates a new instance of URLStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLStorage {
	mock := &URLStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
